---
- name: "Configure Server."
  become: true
  apt:
    update_cache: yes
    upgrade: yes

- name: "Install Node and NPM."
  become: true
  apt:
    name:
      - nodejs
      - npm
    state: latest
    update_cache: yes

- name: "Install PM2."
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
